name:                regex-vm
version:             0.1.0.0
github:              "githubuser/regex-vm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/regex-vm#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- regex-posix
- regex-applicative
- parsec
- optparse-applicative
- criterion
- timeit
- process

library:
  source-dirs: src

executables:
  regex-vm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-vm
  regex-vm-bench:
    main: Bench.main
    source-dirs: bench 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-vm
    - regex-posix
    - regex-applicative
    - timeit
    - process
  regex-vm-crit:
    main: Crit.main
    source-dirs: bench 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-vm
    - regex-posix
    - regex-applicative
    - criterion
tests:
  regex-vm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-vm
